// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfwcntoaeuksexkmvfcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1md2NudG9hZXVrc2V4a212ZmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDUwMjYsImV4cCI6MjA2NzY4MTAyNn0.5uY1QKd-Nzby1b_YnODxm7DpjvRf0wfaccpzcM_v0LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});